on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  release-prepare:
    if: endsWith(github.ref, '/main')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - run: ./script/release-prepare
        shell: bash
        if: endsWith(github.ref, '/main')

      # prepare-env: Push as github bot.
      # https://github.community/t/github-actions-bot-email-address/17204/5
      - name: Prep for git push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash
        if: endsWith(github.ref, '/main')

      - uses: actions/upload-artifact@v4
        with:
          name: release-prepare
          path: |
            package.json
        if: endsWith(github.ref, '/main')

  build:
    needs:
      - release-prepare

    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-20.04
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      # prepare-env: Setup node / pnpm.
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-${{ runner.arch }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-pnpm-store-

      # prepare-env: Setup rust.
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
            !src-tauri/target/release/bundle/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cargo-

      # prepare-env: Tauri deps for linux.
      - if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions/download-artifact@v4
        with:
          name: release-prep
        if: endsWith(github.ref, '/main')

      - run: |
          mv release-prepare/package.json .
        shell: bash
        if: endsWith(github.ref, '/main')

      - run: ./script/prepare-env
        shell: bash

      - run: ./script/build
        shell: bash
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - run: ./script/deploy
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: endsWith(github.ref, '/main')

      - uses: actions/upload-artifact@v4
        with:
          name: wadpunk-${{ matrix.platform }}-${{ runner.arch }}
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/nsis/*.nsis.zip
            src-tauri/target/release/bundle/nsis/*.nsis.zip.sig
            src-tauri/target/release/bundle/macos/*.app.tar.gz
            src-tauri/target/release/bundle/macos/*.app.tar.gz.sig
            src-tauri/target/release/bundle/appimage/*.AppImage.tar.gz
            src-tauri/target/release/bundle/appimage/*.AppImage.tar.gz.sig

  release-finalize:
    needs:
      - build

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        if: endsWith(github.ref, '/main')

      - uses: actions/download-artifact@v4
        with:
          name: release-prep
        if: endsWith(github.ref, '/main')

      - run: |
          mv release-prepare/package.json .
        shell: bash
        if: endsWith(github.ref, '/main')
